### ISSUE TITLE
stuff todo

### ISSUE THREAD

**Issue by orimaromcom** [orimaro123/monday-quiz-game#1]
# TODO:

- [ ] handle 50 50 bug, try to solve it with redux
- [ ] try to solve the design change when doing it
- [ ] fix button highlight after answering the question
- [ ] find a better UI library
- [ ] implement a timer for each question
6. add hints
7. make sure that lifelines are counted down when used
8. change the scoring system
9. add statistics
10. add sounds
11. make the design unified across the application
12. change the instruction page
13. decide what to do with the login/signup
